- hosts: localhost
  vars:
    # プロジェクトのソースパスとドキュメント出力先を指定
    project_source_dir: "./src/main/java"
    project_output_dir: "./doc_doxygen"
    project_name: "Doxygen Project"

  tasks:
    - apt:
        name:
          - doxygen
          - graphviz
        state: present
      become: Yes

    - name: ドキュメント出力ディレクトリを作成
      ansible.builtin.file:
        path: "{{ project_output_dir }}"
        state: directory
        mode: '0755'

    - name: Doxyfileの生成 設定済みのものがない場合
      ansible.builtin.command:
        cmd: doxygen -g
        chdir: "."
        creates: "Doxyfile"

    - name: クラス図を有効にするためのDoxyfile設定変更
      ansible.builtin.lineinfile:
        path: "Doxyfile"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^INPUT\s*=', line: 'INPUT = "{{ project_source_dir }}"' }
        - { regexp: '^PROJECT_NAME\s*=', line: 'PROJECT_NAME = "{{ project_name }}"' }
        - { regexp: '^OUTPUT_DIRECTORY\s*=', line: 'OUTPUT_DIRECTORY = {{ project_output_dir }}' }
        - { regexp: '^HAVE_DOT\s*=', line: 'HAVE_DOT = YES' }
        - { regexp: '^UML_LOOK\s*=', line: 'UML_LOOK = YES' }
        - { regexp: '^EXTRACT_ALL\s*=', line: 'EXTRACT_ALL = YES' }
        - { regexp: '^CLASS_GRAPH\s*=', line: 'CLASS_GRAPH = YES' }
        - { regexp: '^COLLABORATION_GRAPH\s*=', line: 'COLLABORATION_GRAPH = YES' }
        - { regexp: '^RECURSIVE\s*=', line: 'RECURSIVE = YES' }
        - { regexp: '^CALLER_GRAPH\s*=', line: 'CALLER_GRAPH = YES' }
        - { regexp: '^CLASS_DIAGRAMS\s*=', line: 'CLASS_DIAGRAMS = YES' }
        - { regexp: '^EXTRACT_PRIVATE\s*=', line: 'EXTRACT_PRIVATE = YES' }

    - name: Doxygenを実行してドキュメントを生成
      ansible.builtin.command:
        cmd: doxygen Doxyfile
        chdir: "."
      register: doxygen_result

    - name: Doxygenからクラス図を抽出する
      ansible.builtin.command:
        cmd: python3 site_doxygen.py
        chdir: "."

    - name: 実行結果の表示
      ansible.builtin.debug:
        msg: "ドキュメントが {{ project_output_dir }}/html/index.html に生成されました。"
      when: doxygen_result.rc == 0
